version: "3"

services:
  rabbitmq:
    container_name: "rabbitmq"
    image: rabbitmq:3.10.7-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      # AMQP protocol port
      - '5672:5672'
      # HTTP management UI
      - '15672:15672'
    volumes:
      - data:/var/lib/rabbitmq/
      - log:/var/log/rabbitmq

volumes:
  data:
  log: